spring.application.name=spring-oauth2-resource-server

#db
#server.port=8081 en pause pour tester gateway
spring.datasource.url = ${MYSQL_URL_SPRING_OAUTH2_RESOURCE_SERVER}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}


#jpa
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=${SERVLET_CONTEXT_PATH}


#swagger
springdoc.api-docs.path=${API_DOCS_PATH}

#security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

#mongodb
spring.mongodb.uri=${MONGO_URI}

# Optionnel : Pour afficher les requêtes MongoDB dans la console lors des tests
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Supprime les warnings MongoDB au démarrage
logging.level.org.mongodb.driver.cluster=ERROR

#REDIS
# CONFIGURATION REDIS (Pour se connecter au Docker de ta VM)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Optionnel : Temps de vie (TTL) par défaut du cache (ex: 10 minutes)
spring.cache.redis.time-to-live=3m